import { config } from 'dotenv';
config();

import '@/ai/flows/summarize-pdf.ts';
import '@/ai/flows/extract-information-from-pdf.ts';
import '@/ai/flows/classify-subject-level.ts';
import '@/ai/flows/classify-discipline.ts';
import '@/ai/flows/classify-sub-discipline.ts';
import '@/ai/flows/classify-participants-group.ts';
import '@/ai/flows/classify-country-region.ts';
import '@/ai/flows/classify-sample-size.ts';
import '@/ai/flows/classify-ai-tech-type.ts';
import '@/ai/flows/classify-emi-context.ts';
import '@/ai/flows/classify-intervention-roles.ts';
import '@/ai/flows/classify-roles-skills.ts';
import '@/ai/flows/classify-integration-mode.ts';
import '@/ai/flows/classify-ethics-focus.ts';
import '@/ai/flows/classify-teacher-support.ts';
import '@/ai/flows/classify-outcome-category.ts';
import '@/ai_flows/classify-evidence-strength.ts';
import '@/ai_flows/classify-measures.ts';
import '@/ai_flows/classify-design-type.ts';
import '@/ai_flows/classify-ai-disclosure-required.ts';
import '@/ai/flows/classify-ai-use-instructions-provided.ts';
